import { redirect, useRouter } from "next/navigation";
import getCurrentUser from "../actions/getCurrentUser";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Genius | Auth',
  description: 'Generated by create next app',
}

const AuthLayout = async({
    children
  }: {
    children: React.ReactNode;
  }) => {
    const user = await getCurrentUser();
  
    if(user){
        redirect('/dashboard')
    }
    return ( 
      <main className="h-full bg-[#111827] flex items-center justify-center">
        {children}
      </main>
    );
  }
   
  export default AuthLayout;